# Project: 项目1
# Makefile created by Dev-C++ 5.9.2

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = 类与对象练习？？.o
LINKOBJ  = 类与对象练习？？.o
LIBS     = -L"D:/GeePlayerDownload/MinGW64/lib32" -L"D:/GeePlayerDownload/MinGW64/x86_64-w64-mingw32/lib32" -static-libgcc -mwindows -m32 -g3
INCS     = -I"D:/GeePlayerDownload/MinGW64/include" -I"D:/GeePlayerDownload/MinGW64/x86_64-w64-mingw32/include" -I"D:/GeePlayerDownload/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include"
CXXINCS  = -I"D:/GeePlayerDownload/MinGW64/include" -I"D:/GeePlayerDownload/MinGW64/x86_64-w64-mingw32/include" -I"D:/GeePlayerDownload/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include" -I"D:/GeePlayerDownload/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include/c++"
BIN      = 项目1.exe
CXXFLAGS = $(CXXINCS) -m32 -g3
CFLAGS   = $(INCS) -m32 -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

类与对象练习？？.o: 类与对象练习？？.cpp
	$(CPP) -c 类与对象练习？？.cpp -o 类与对象练习？？.o $(CXXFLAGS)
