# Project: ÏîÄ¿1
# Makefile created by Dev-C++ 5.9.2

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = kaobei.o
LINKOBJ  = kaobei.o
LIBS     = -L"D:/GeePlayerDownload/MinGW64/lib" -L"D:/GeePlayerDownload/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -mwindows -g3
INCS     = -I"D:/GeePlayerDownload/MinGW64/include" -I"D:/GeePlayerDownload/MinGW64/x86_64-w64-mingw32/include" -I"D:/GeePlayerDownload/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include"
CXXINCS  = -I"D:/GeePlayerDownload/MinGW64/include" -I"D:/GeePlayerDownload/MinGW64/x86_64-w64-mingw32/include" -I"D:/GeePlayerDownload/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include" -I"D:/GeePlayerDownload/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include/c++"
BIN      = ¿½±´.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

kaobei.o: kaobei.cpp
	$(CPP) -c kaobei.cpp -o kaobei.o $(CXXFLAGS)
